# Generated by Django 5.0.6 on 2026-07-09 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crash_point', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('FLYING', 'Flying'), ('CRASHED', 'Crashed')], default='WAITING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='core_gamero_status_cd47ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('cashout_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
                ('game_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='core.gameround')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'game_round'], name='core_bet_user_id_92e4c4_idx'), models.Index(fields=['status', 'game_round'], name='core_bet_status_4d76f8_idx')],
                'unique_together': {('user', 'game_round')},
            },
        ),
    ]
