# Generated by Django 5.0.6 on 2026-07-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deposittransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='half_cashout_done',
            field=models.BooleanField(default=False),
        ),
    ]
